# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: "https://moonlanding.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Moonlanding Network"
description: "ICO rating, listing, and calendar with details on top ICOs from various industries. Learn more about ICO funding, whitepaper, dates, teams, and roadmaps."
keywords: "ico alert, ico analysis, ico list, list of icos, list of crypto icos, initial coin offering, active icos, upcoming initial coin offerings, upcoming icos, active icos, cryptocurrency icos, new crypto icos, crypto icos, new icos, crypto ico list, comprehensive ico list, future icos, discover icos, token sale calendar, ico calendar, crowdsale calendar, crowdsales, token sales"
logo: "/images/logo-image.png"
# Build settings
markdown: kramdown
timezone: Greenwich
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - _site
  - node_modules
keep_files: [images]
#plugins:
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache

collections:
  coins:
    output: true
    permalink: /:collection/:name

