backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/images" # Media files will be stored in the repo under images
collections:
 - name: "coins"
   label: "Coins"
   editor:
    preview: false
   folder: _coins
   create: true
   extension: html
   format: frontmatter
   fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "coindetail"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Meta Description", name: "metadesc", widget: "string", required: false }
    - {label: "Meta Keywords", name: "metakeywords", widget: "string", required: false}
    - label: "Date Added"
      name: "date-added"
      widget: "date"
      default: 
      format: "YYYY-MM-DD"
    - name: "ico"
      label: "Basic ICO Listing Information"
      widget: object
      fields:
       - {label: "Cancelled", name: "cancelled", widget: "boolean", default: false}
       - {label: "ICO Name", name: "name", widget: "string" }
       - {label: "Token Name", name: "token-name", widget: "string" }
       - {label: "Logo", name: "logo", widget: "image", required: false}
       - {label: "Category", name: "category", widget: "string", required: false }
       - {label: "Two Word Description", name: "shortdesc", widget: "string",required: false }
       - {label: "Featured", name: "featured", widget: "boolean", default: false}
       - label: "Featured Till"
         name: "featured-till"
         widget: "date"
         default: ""
         format: "YYYY-MM-DD"
       - {label: "Show Rating For Featured", name: "show-rating", widget: "boolean", default: false}
       - {label: "Top Banner Advert", name: "topbanner", widget: "boolean", default: false }
       - {label: "Top Banner Advert Blurb", name: "topbanner-content", widget: "string", required: false }
       - {label: "Video Link", name: "video", widget: "string", required: false }
       - {label: "Whitepaper Link", name: "whitepaper", widget: "string", required: false }
       - {label: "Crowdsale Link", name: "crowdsale", widget: "string", required: false }
       - {label: "Main Description", name: "desc", widget: "text", required: false }
       - name: "tags"
         label: "Tags"
         widget: list
         required: false
         fields:
           - {label: "Tag", name: "tag", widget: "string"}
    - {label: "ICO Rating", name: "moonability", widget: "string", required: false }
    - name: "whitelist"
      label: "Whitelist Informtaion"
      widget: object
      fields:
       - {label: "Whitelist Present", name: "status", widget: "boolean", default: false}
       - name: "type"
         label: "Whitelist Type"
         widget: select
         options:
          - { label: "Whitelist", value: "Whitelist" }
          - { label: "Whitelist + KYC", value: "Whitelist + KYC" }
       - {label: "Date Not Announced", name: "no-date", widget: "boolean", default: false }
       - label: "Whitelist Start Date"
         name: "start-date"
         widget: "date"
         default: ""
         format: "YYYY-MM-DD"
       - label: "Whitelist End Date"
         name: "end-date"
         widget: "date"
         default: ""
         format: "YYYY-MM-DD"
    - name: "token"
      label: "Token Meta Information"
      widget: object
      fields:
       - {label: "Token Type", name: "type", widget: "string", required: false }
       - {label: "Project Location", name: "location", widget: "string", required: false }
       - label: "Announced Date"
         name: "announced"
         widget: "date"
         default: ""
         format: "MMMM-D-YYYY"
    - name: "progress"
      label: "ICO Progress"
      widget: object
      fields:
       - label: "Total Tokens"
         name: "total"
         widget: "number"
         default: 0
         valueType: "int"
       - label: "Collected"
         name: "collected"
         widget: "number"
         default: 0
         valueType: "int"
    - name: "pre-ico"
      label: "Pre ICO Information"
      widget: object
      fields:
       - {label: "Date Not Announced", name: "no-date", widget: "boolean", default: false }
       - label: "Pre ICO Start Date"
         name: "start-date"
         widget: "date"
         default: ""
         format: "MMM-DD-YYYY"
       - label: "Pre ICO End Date"
         name: "end-date"
         widget: "date"
         default: ""
         format: "MMM-DD-YYYY"
       - name: "mvp"
         label: "MVP"
         widget: select
         options:
          - { label: "Yes", value: "Yes" }
          - { label: "No", value: "No" }
          - { label: "Alpha", value: "Alpha" }
       - {label: "Soft Cap", name: "soft-cap", widget: "string", required: false }
       - {label: "Hard Cap", name: "hard-cap", widget: "string", required: false }
       - name: "contribution-size"
         label: "Contribution Size"
         widget: object
         fields:
          - {label: "Minimum Contribution Value in USD", name: "usd", widget: "string", required: false }
          - {label: "Minimum Contribution Value in ETH", name: "eth", widget: "string", required: false }
       - name: "conversion"
         label: "Conversion"
         widget: object
         fields:
          - {label: "Token Value in USD", name: "usd", widget: "string", required: false }
          - {label: "Token Value in ETH", name: "eth", widget: "string", required: false }
          - {label: "Token Value in BTC", name: "btc", widget: "string", required: false }
       - {label: "Token Transferability", name: "token-issue", widget: "string", required: false }
       - {label: "Pre ICO Bonus", name: "pre-ico-bonus", widget: "string", required: false }
    - name: "ico-detail"
      label: "ICO Information"
      widget: object
      fields:
       - {label: "Date Not Announced", name: "no-date", widget: "boolean", default: false }
       - label: "ICO Start Date"
         name: "start-date"
         widget: "date"
         default: ""
         format: "MMM-DD-YYYY"
       - label: "ICO End Date"
         name: "end-date"
         widget: "date"
         default: ""
         format: "MMM-DD-YYYY"
       - name: "mvp"
         label: "MVP"
         widget: select
         options:
          - { label: "Yes", value: "Yes" }
          - { label: "No", value: "No" }
          - { label: "Alpha", value: "Alpha" }
       - {label: "Soft Cap", name: "soft-cap", widget: "string", required: false }
       - {label: "Hard Cap", name: "hard-cap", widget: "string", required: false }
       - name: "contribution-size"
         label: "Contribution Size"
         widget: object
         fields:
          - {label: "Minimum Contribution Value in USD", name: "usd", widget: "string", required: false }
          - {label: "Minimum Contribution Value in ETH", name: "eth", widget: "string", required: false }
       - {label: "Total Supply", name: "total-supply", widget: "string", required: false }
       - {label: "Investor Supply", name: "investor-supply", widget: "string", required: false }
       - name: "supply-distribution"
         label: "Supply Distribution"
         widget: list
         fields:
          - {label: "Name and Value. (eg, Core team: 10%)", name: "distribution-item", widget: "string", required: false }
       - name: "conversion"
         label: "Conversion"
         widget: object
         fields:
          - {label: "Token Value in USD", name: "usd", widget: "string", required: false }
          - {label: "Token Value in ETH", name: "eth", widget: "string", required: false }
          - {label: "Token Value in BTC", name: "btc", widget: "string", required: false }
       - {label: "Token Transferability", name: "token-issue", widget: "string", required: false }
       - {label: "Pre ICO Bonus", name: "bonus", widget: "string", required: false }
    - name: "team"
      label: "Team Information"
      widget: list
      fields:
       - {label: "Name", name: "name", widget: "string", required: false}
       - {label: "Display Picture", name: "image", widget: "image", required: false }
       - {label: "Position", name: "position", widget: "string", required: false }
       - {label: "Linkedin Profile", name: "linkedin", widget: "string",required: false }
    - name: "social"
      label: "ICO Website & Social Links"
      widget: object
      fields:
       - {label: "Website", name: "website", widget: "string", required: false }
       - {label: "Facebook", name: "facebook", widget: "string", required: false }
       - {label: "Twitter", name: "twitter", widget: "string", required: false }
       - {label: "Telegram", name: "telegram", widget: "string", required: false }
       - {label: "Medium", name: "medium", widget: "string", required: false }
    - name: "ico-participation-details"
      label: "ICO Participation Terms"
      widget: object
      fields:
       - name: "currencies-accepted"
         label: "Currencies Accepted"
         widget: list
         fields:
          - {label: "Currency", name: "currency", widget: "string" ,required: false  }
       - name: "countries-notallowed"
         label: "Countries Not Allowed"
         widget: list
         fields:
          - {label: "Country", name: "country", widget: "string",required: false  }
    - {label: "Input Twitter Username to Display Feed", name: "twitter-username", widget: "string", required: false }      
 - name: "configuration"
   label: "Configuration"
   editor:
    preview: false
   files:
    - name: "configuration"
      label: "Basic Site Information"
      file: "_data/configuration.yml"
      fields: 
       - name: "config"
         label: "Configuration"
         widget: list
         disableAdd: true
         fields:
          - name: "listing-price"
            label: "Banner Advertisement Listing Price"
            widget: object
            fields:
             - {label: "For Top Banner", name: "topbanner", widget: "string" }
             - {label: "For Featured", name: "featured", widget: "string" }
          - name: "site-info"
            label: "Basic Site Information"
            widget: object
            fields:
             - {label: "Logo Name", name: "logo-name", widget: "string" }
             - {label: "Logo Name Subtitle", name: "logo-name-subtitle", widget: "string" }
             - {label: "Logo Image", name: "logo-image", widget: "image" }
             - {label: "Description", name: "description", widget: "text" }
          - name: "social"
            label: "Social Links"
            widget: object
            fields:
             - {label: "Twitter Feed Username", name: "twitter-username", widget: "string" }
             - {label: "Twitter Link", name: "twitter-link", widget: "string" }
             - {label: "Facebook Link", name: "facebook-link", widget: "string" }
             - {label: "Telegram Chat", name: "telegram-chat", widget: "string" }
             - {label: "Telegram Broadcast", name: "telegram-broadcast", widget: "string" }
    - name: "footer"
      label: "Footer Links"
      file: "_data/footer.yml"
      fields: 
       - name: "footer"
         label: "Footer Links"
         widget: list
         disableAdd: true
         fields:
          - name: "links-col-1"
            label: "Footer Links Column 1"
            widget: list
            fields:
             - {label: "Title", name: "name", widget: "string" }
             - {label: "URL", name: "href", widget: "string" }  
          - name: "links-col-2"
            label: "Footer Links Column 2"
            widget: list
            fields:
             - {label: "Title", name: "name", widget: "string" }
             - {label: "URL", name: "href", widget: "string" }          